server:
  port: 8073
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**
          - id: rent-service
            uri: lb://rent-service
            predicates:
              - Path=/api/rents/**
          - id: vehicle-service
            uri: lb://vehicle-service
            predicates:
              - Path=/api/vehicles/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0