version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: user_service
      POSTGRES_USER: root
    volumes:
      - ./pgdata:/var/lib/postgresql/data